# Generated by Django 5.1 on 2024-09-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestimentoModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('valor_investimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_retorno', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'investimento',
            },
        ),
    ]
